[project]
name = "ai-papers-cleaner"
version = "0.1.0"
description = "Extract text from papers PDFs and abstracts, and remove uninformative words."
authors = ["George Araujo <george.gcac@gmail.com>"]
license = "BSD-3"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "ftfy>=6.3.1",
    "inflect>=7.5.0",
    "nltk>=3.9.3",
    "pandas>=3.0.1",
    "pyarrow>=23.0.1",
    "pyenchant>=3.3.0",
    "pypdfium2>=5.5.0",
    "tqdm>=4.67.3",
]
